### PR TITLE
Refactoring of ReverseString.java and renaming of classes to compile

### PR DESCRIPTION
**Pull request by singloon**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — COMMENTED** [review]
@singloon 

**Thank you for contributing!**
But for getting merge your pull request you have to make contribution of your own code. 
If you found changes you could raise an issue but it's ok you made a PR.
Read README.md for more details.
Don't hesitate to give a ⭐

**Comment by singloon** [comment]
Just noticed your repo has been excluded from Hacktoberfest.

Most of the code merged wasn't compiling which I fixed in the PR and I also refactored and provided an improved reverse String implementation. 

You'll want to test or at least compile the code before merging PRs.

**Comment by CODING-Enthusiast9857** [comment]
I have been compiling codes before merging PRs and if you run the java code in any online compiler you won't get any error.
About excluding PRs, The PRs which not get merged only those are excluded.

**Comment by singloon** [comment]
image
image

**Comment by singloon** [comment]
image

**Comment by CODING-Enthusiast9857** [comment]
@singloon 


Your PR was closed that's why they are showing excluded. Your PR should be merged in order to acceptance...

**Comment by singloon** [comment]
Read the explanation.... 
`Your PR/MR was submitted to a repository that has been excluded from Hacktoberfest as it does not follow the values of the event. It will not count towards your participation.`

**Comment by CODING-Enthusiast9857** [comment]
Only Merged PRs have been accepted.... 
If you have any doubt about the above sentence then make a new pull request with your own code contribution and clarify it

**Comment by singloon** [comment]
> @singloon
> 
> Your PR was closed that's why they are showing excluded. Your PR should be merged in order to acceptance...

Your repo was marked as excluded before the PR was closed. I'll recommend reading https://hacktoberfest.com/participation/

**Comment by CODING-Enthusiast9857** [comment]
I have read before that participating....


**YOUR PR/MRS MUST BE MERGED**, HAVE THE “HACKTOBERFEST-ACCEPTED” LABEL, OR HAVE AN OVERALL APPROVING REVIEW.

If your PR/MR is being accepted for Hacktoberfest via an overall approving review **it must also not be closed.**

ONCE YOUR PR/MRS PASS ALL THE CHECKS ABOVE, IT WILL BE ACCEPTED FOR HACKTOBERFEST AFTER THE 7-DAY REVIEW PERIOD.

**Comment by singloon** [comment]
The issue we're discussing is your repo is excluded from Hacktoberfest. Nothing to do with my PR.

Which means from the website  https://hacktoberfest.com/participation/ 

`[ EXCLUDED ]

REPOS THAT GO AGAINST HACKTOBERFEST’S VALUES WILL BE EXCLUDED FROM QUALIFICATION AND PR/MRS MADE TO THOSE REPOS WON’T COUNT.
Found a repository that goes against the values of Hacktoberfest? [LET US KNOW AND WE’LL TAKE A LOOK.](https://hacktoberfest.com/report/)`

**Pull request closed without merging**
