### PR TITLE
Adding Fibonacci sequence

### PR DESCRIPTION
**Pull request by fawazsiddiqi**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@fawazsiddiqi 


**Thank you for contributing!**

Please add yourself to **CONTRIBUTORS.md**
Don't hesitate to give a ⭐

**Comment by fawazsiddiqi** [comment]
@CODING-Enthusiast9857 Done!

**Review by CODING-Enthusiast9857 — APPROVED** [review]

**Comment by fawazsiddiqi** [comment]
@CODING-Enthusiast9857 can you add the hacktoberfest tag to the repo? As it is getting excluded on hacktoberfest...

**Comment by fawazsiddiqi** [comment]
@CODING-Enthusiast9857 for some reason the repo is getting excluded at Hacktoberfest...

**Pull request merged**
