### PR TITLE
Added java program to Check Magic Number

### PR DESCRIPTION
**Pull request by surjendu104**
Added java program to Check Magic Number. 
Do check it out and merge it

### CODE REVIEW

**Comment by surjendu104** [comment]
Hey you have merged the branch but not gave the label. PS give label. If any problem let me know

**Comment by surjendu104** [comment]
Is it not accepted for Hactoberfest

**Comment by CODING-Enthusiast9857** [comment]
@surjendu104 

That label is for your 1st PR only. You have made your 1st PR and I have already given label to it.

**Comment by surjendu104** [comment]
Thanks,I thought that every PR should be labelled..thanks again

**Comment by CODING-Enthusiast9857** [comment]
Don't mention

**Pull request merged**
