### PR TITLE
fibonacci series

### PR DESCRIPTION
**Pull request by PinetheApple**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@PinetheApple 


**Thank you for contributing!**

Your code is not giving correct answer.
Please make the require changes
Don't hesitate to give a ⭐

**Review by PinetheApple — COMMENTED** [review]
i believe it should work properly now

**Comment by CODING-Enthusiast9857** [comment]
@PinetheApple 

It is still not working

**Comment by PinetheApple** [comment]
> @PinetheApple
> 
> It is still not working

i dont know how to resolve conflicts so i think i'll just discard the changes and reupload the file with the fix
basically all that has to be changed is this
- System.out.println("the number is: "+fib(n-1));
instead of 
- System.out.println("the number is: "+fib(n));

**Pull request closed without merging**
